#!/usr/bin/env python3
"""
Post flaky test results as a comment on the GitHub PR.
"""
import json
import os
import sys

import requests


def format_result_table(results):
    """Format test results as a markdown table."""
    if not results:
        return "No detailed results available."

    # Show only failed runs in the table
    failed_runs = [r for r in results if not r["passed"]]
    if not failed_runs:
        return "All test runs passed!"

    # Limit to first 10 failures to keep comment size reasonable
    failed_runs = failed_runs[:10]

    table = "| Attempt | Exit Code | Error |\n"
    table += "|---------|-----------|-------|\n"

    for run in failed_runs:
        attempt = run["attempt"]
        exit_code = run["exit_code"] if run["exit_code"] is not None else "N/A"
        stderr = run["stderr"][:100].replace("\n", " ")  # Truncate long errors
        table += f"| {attempt} | {exit_code} | {stderr} |\n"

    if len([r for r in results if not r["passed"]]) > 10:
        table += f"\n*... and {len([r for r in results if not r['passed']]) - 10} more failures*\n"

    return table


def create_comment_body(result):
    """Create the PR comment body."""
    total_runs = result.get("total_runs", 0)
    failures = result.get("failures", 0)
    repro_rate = result.get("repro_rate", 0)

    # Determine the emoji and severity
    if repro_rate > 0.9:
        emoji = "🔴"
        severity = "CRITICAL"
        message = "This test consistently fails and is likely a real bug, not flaky."
    elif repro_rate > 0.5:
        emoji = "🟠"
        severity = "HIGH"
        message = "This test fails frequently and should be investigated."
    elif repro_rate > 0.1:
        emoji = "🟡"
        severity = "MEDIUM"
        message = "This test shows flaky behavior."
    elif repro_rate > 0:
        emoji = "🟢"
        severity = "LOW"
        message = "This test shows occasional flakiness."
    else:
        emoji = "✅"
        severity = "NONE"
        message = "No flakiness detected - test appears stable."

    comment = f"""## {emoji} Flaky Test Detection Results

**Severity:** {severity}

{message}

### Summary
- **Total runs:** {total_runs}
- **Failures:** {failures}
- **Reproduction rate:** {repro_rate * 100:.1f}%

### Failed Test Runs
{format_result_table(result.get('results', []))}

---
<details>
<summary>What is a flaky test?</summary>

A flaky test is a test that sometimes passes and sometimes fails without any code changes. Common causes:
- Race conditions
- Timing dependencies
- Random data generation
- External service dependencies
- Resource contention

**Recommendation:** If the repro rate is above 10%, investigate and fix the root cause before merging.
</details>

*🤖 Automatically generated by [Flaky Test Detector](https://github.com/{os.environ.get('GITHUB_REPOSITORY', '')})*
"""
    return comment


def main():
    github_token = os.environ.get("GITHUB_TOKEN")
    pr_number = os.environ.get("PR_NUMBER")
    repository = os.environ.get("GITHUB_REPOSITORY")

    if not github_token:
        print("ERROR: GITHUB_TOKEN not set")
        sys.exit(1)

    if not pr_number:
        print("WARNING: PR_NUMBER not set, skipping PR comment")
        sys.exit(0)

    # Load results
    try:
        with open("flaky_test_results.json") as f:
            result = json.load(f)
    except FileNotFoundError:
        print("ERROR: Results file not found")
        sys.exit(1)

    # Create comment body
    comment_body = create_comment_body(result)

    # Post comment to PR
    url = f"https://api.github.com/repos/{repository}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    data = {"body": comment_body}

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        print(f"✅ Posted comment to PR #{pr_number}")
    except requests.exceptions.RequestException as e:
        print(f"❌ Failed to post PR comment: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
